from django.urls import path
from . import views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<str:code>/', views.activate, name='activate'),
    path('buyer_center/', views.buyer_center, name='buyer_center'),
    path('shop_center/', views.shop_center, name='shop_center'),
    path('editing/',views.editing,name='editing'),
    path('forget_password/', views.forget_password, name='forget_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('reset_password/<str:code>/', views.reset_password, name='reset_password'),
    path('add_address/',views.add_address, name='add_address'),
    path('manage_goods/',views.manage_goods,name='manage_goods'),
    path('manage_goods/add_goods/',views.add_goods,name='add_goods'),
    path('manage_goods/delete_goods/<int:id>',views.delete_goods,name='delete_goods'),
    path('manage_goods/is_selling/<int:id>',views.is_selling,name='is_selling'),
    path('manage_goods/is_not_selling/<int:id>', views.is_not_selling, name='is_not_selling'),
    path('manage_goods/edit_goods/<int:id>',views.edit_goods,name='edit_goods'),
    path('check_goods/<int:id>',views.check_goods,name ='check_goods'),
    path('category/<int:num>',views.category,name='category'),
    path('shopping_car/',views.shopping_car,name='shopping_car'),
    path('shopping_car/delete_shopping_car/<int:id>', views.delete_shopping_car, name='delete_shopping_car'),
    path('my_money/',views.my_money,name='my_money'),
    path('buying/<int:id>', views.buying, name='buying'),
    path('create_order/<int:id>',views.create_order,name='create_order'),
    path('my_order/',views.my_order,name='my_order'),
    path('my_order/waiting_for_paying/',views.waiting_for_paying,name='waiting_for_paying'),
    path('my_order/waiting_for_sending/',views.waiting_for_sending,name='waiting_for_sending'),
    path('my_order/waiting_for_receiving/',views.waiting_for_receiving,name='waiting_for_receiving'),
    path('my_order/waiting_for_comment/',views.waiting_for_comment,name='waiting_for_comment'),
    path('my_order/done/',views.done,name='done'),
    path('my_order/waiting_for_dispose/',views.waiting_for_dispose,name='waiting_for_dispose'),
    path('my_order/have_disposed/',views.have_disposed,name='have_disposed'),
    path('my_order/check_order/<int:id>',views.check_order,name='check_order'),
    path('my_order/delete_order/<int:id>',views.delete_order,name='delete_order'),
    path('check_shop/<int:id>',views.check_shop,name='check_shop'),
    path('make_comment/<int:id>',views.make_comment,name='make_comment'),
    path('goods_comment/<int:id>',views.goods_comment,name='goods_comment'),
    path('goods_comment/delete_comment/<int:id>',views.delete_comment,name='delete_comment'),
    path('goods_comment/reply/<int:id>',views.reply,name='reply'),
    path('goods_comment/delete_reply/<int:id>',views.delete_reply,name='delete_reply'),
    path('search/',views.search,name='search'),
]