# Generated by Django 2.2 on 2020-12-04 12:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=128, verbose_name='收件人')),
                ('phone', models.CharField(max_length=128, verbose_name='手机号')),
                ('province', models.CharField(max_length=128, verbose_name='省份')),
                ('city', models.CharField(max_length=128, verbose_name='城市')),
                ('detail', models.CharField(max_length=128, verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '买家地址管理',
                'verbose_name_plural': '买家地址管理',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否激活')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y%m%d/')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_shopkeeper', models.IntegerField(default=0)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='买家钱包')),
            ],
            options={
                'verbose_name': '买家信息管理',
                'verbose_name_plural': '买家信息管理',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='商品名')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('picture', models.ImageField(upload_to='avatar/%Y%m%d/', verbose_name='商品封面图')),
                ('category', models.IntegerField(choices=[(0, '百货'), (1, '女装'), (2, '男装'), (3, '母婴'), (4, '美妆'), (5, '食品'), (6, '鞋包'), (7, '家纺'), (8, '运动'), (9, '书籍')], default=0, verbose_name='商品类别')),
                ('is_selling', models.IntegerField(default=0, verbose_name='是否上架')),
                ('stock', models.IntegerField(default=1, verbose_name='商品库存')),
                ('sales', models.IntegerField(default=0, verbose_name='商品销量')),
            ],
            options={
                'verbose_name': '商品信息管理',
                'verbose_name_plural': '商品信息管理',
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('shop_name', models.CharField(blank=True, max_length=128, verbose_name='店铺名')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y%m%d/')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否激活')),
                ('is_shopkeeper', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='卖家钱包')),
            ],
            options={
                'verbose_name': '卖家信息管理',
                'verbose_name_plural': '卖家信息管理',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('the_buyer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estore.Buyer', verbose_name='买家')),
                ('the_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=128, verbose_name='商品名')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('goods_picture', models.ImageField(upload_to='avatar/%Y%m%d/', verbose_name='商品封面图')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Address', verbose_name='地址')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Buyer', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='the_shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Shopkeeper', verbose_name='所属店铺'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('commenter', models.CharField(max_length=128, verbose_name='评论人')),
                ('reply', models.TextField(verbose_name='回复')),
                ('the_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Goods')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='the_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Buyer'),
        ),
    ]
