# Generated by Django 2.2 on 2020-12-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcar',
            name='count',
        ),
    ]
