# Generated by Django 2.2 on 2020-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_remove_shoppingcar_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods_price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
    ]
