# Generated by Django 2.2 on 2020-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_order_shop_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter',
            field=models.CharField(blank=True, max_length=128, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.TextField(blank=True, verbose_name='回复'),
        ),
    ]
