# Generated by Django 2.2 on 2020-12-08 03:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_auto_20201205_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='商品详情'),
        ),
    ]
